### ISSUE TITLE
Add config option to set an alternative ./public/ directory source

### ISSUE THREAD

**Issue by kkanyingi** [jonelantha/gatsby-s3-action#5]
It would be nice to have the option to set a custom ./public directory incase the users gatsby project is not in the root of the repo.

currently I get this error when running the deploy script
`The user-provided path ./public/ does not exist.`

**Comment by kkanyingi** [comment]
#6

**Comment by jonelantha** [comment]
Implemented in #6 
Thanks @kkanyingi for your contribution 😄
