### ISSUE TITLE
Avoid deleting deleting everything in s3-bucket

### ISSUE THREAD

**Issue by HashemKhalifa** [jonelantha/gatsby-s3-action#9]
Hi @jonelantha, 
Thanks for the amazing work.

 I have an issue with emptying the bucket as there are different places deploying into the same bucket.

is there's a way to delete only gatsby files instead of everything?

Kind regards,
Hashem

**Comment by jonelantha** [comment]
Hi Hashem
Many thanks for your feedback.
I'm currently looking into the available options for this and hope to have an updated version available this week.

**Comment by HashemKhalifa** [comment]
@jonelantha thanks a lot sounds great, would be also nice to have an option for invalidation paths.

**Comment by jonelantha** [comment]
I've just released version v1.2.0 which adds a number of new fields:

- `dest-s3-path`: the destination S3 Path
- `cloudfront-path-to-invalidate`: The path to invalidate on the CloudFront distribution (default: /*)
- `sync-delete`: allows control over the behaviour which deletes files on S3 which are not in the latest Gatsby build (default is 'true' which was the existing behaviour)

Please see the readme for details

Unfortunately there's no way I can think of to just delete Gatsby files as potentially they could be any file. Hopefully the additions in v1.2.0 should help out though.
